### ISSUE TITLE
change item for outfit

### ISSUE THREAD

**Issue by matheusjp2** [gesior/open-tibia-library#1]
how to change to generate outfit?

**Comment by matheusjp2** [comment]
`
![Screenshot_6](https://user-images.githubusercontent.com/32050328/76364521-2598a080-6304-11ea-8c58-6cae097fd4a3.png)
`
have to change to unite everything in gif?
exemplo
![creature](https://user-images.githubusercontent.com/32050328/76364745-6690b500-6304-11ea-92cb-9c658fc81980.gif)

**Comment by gesior** [comment]
@matheusjp2 
On evening I will post here PHP script that make animations from images generated by this library.

Images generated by this library should be compatible with PHP scripts from:
https://otland.net/threads/outfit-images-10-99.251634/
(just replace folder with images)

**Comment by gesior** [comment]
@matheusjp2 
Files and instruction are there:
https://github.com/gesior/open-tibia-library/tree/master/tools/colored-outfit-images-generator
