### ISSUE TITLE
License

### ISSUE THREAD

**Issue by cypheredd** [gesior/open-tibia-library#16]
@gesior can I use this library for my project? Can you set a license you are sharing it under

**Comment by gesior** [comment]
> 

I will add LICENSE file in next release.
License is:
Do whatever you want. Like MIT, but you don't even have to mention author or source (ex. this git repo) of code.

**Comment by cypheredd** [comment]
@gesior  Thank you for the reply. I'm using this project to create my own game client using the file managers. This is awesome and you're awesome. 💜

Also I think I will try and ship the modules folder into an NPM package; I'll fork and open a PR, if you receive it we can add it to this repo
