### ISSUE TITLE
Possibility to extract item in .gif format

### ISSUE THREAD

**Issue by rokamdev** [gesior/open-tibia-library#18]
It would be interesting to have the option of extracting items in .gif format, as the vast majority of new items have effects

**Comment by gesior** [comment]
> It would be interesting to have the option of extracting items in .gif format, as the vast majority of new items have effects

I could not find any JS library able to process multiple PNG images into GIF animation.
I made generator ( https://item-images.ots.me/generator-animated-items/ ) that exports all animation frames into 1 PNG and then you have to use this PHP tool:
https://github.com/gesior/open-tibia-library/tree/master/tools/item-image-frames-to-animated-gif-converter
to merge these animation frames into .gif or animated .png (APNG - animated PNG).
